export const ON_PENDING="PENDING";
export const ON_FULFILLED="FULFILLED";
export const ON_REJECTED="REJECTED";
export const RESET="RESET"
export const LOGOUT="LOGOUT"
export const ON_FULFILLED_LOGIN="FULFILLED_LOGIN"
export const ON_FULFILLED_SIGNUP="FULFILLED_SIGNUP"
export const ON_FORGOT_PASSWORD="FORGOT_PASSWORD"